# Generated by Django 5.2.6 on 2025-09-06 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monto del Alquiler",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Contrato Activo"),
                ),
                (
                    "maintenance_paid_by_owner",
                    models.BooleanField(
                        default=True,
                        verbose_name="Mantenimiento pagado por propietario",
                    ),
                ),
                (
                    "apartment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease",
                        to="estates.apartment",
                        verbose_name="Apartamento",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "OWNER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases_as_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        limit_choices_to={"role": "TENANT"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leases_as_tenant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inquilino",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Emisión"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PAID", "Pagada"),
                            ("OVERDUE", "Vencida"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.lease",
                        verbose_name="Contrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="leases/contracts/", verbose_name="Documento PDF"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="billing.lease",
                        verbose_name="Contrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto Pagado"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CC", "Tarjeta de Crédito"),
                            ("TRANSFER", "Transferencia Bancaria"),
                            ("CASH", "Efectivo"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.invoice",
                        verbose_name="Factura",
                    ),
                ),
            ],
        ),
    ]
