# Generated by Django 5.2.6 on 2025-09-06 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Edificio"
                    ),
                ),
                ("address", models.TextField(verbose_name="Dirección")),
                (
                    "rules_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="estates/rules/",
                        verbose_name="Normas del Edificio (PDF)",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "SUPERVISOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_estate",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supervisor Asignado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, verbose_name="Número de Apartamento/Local"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "OWNER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_apartments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["TENANT", "RESIDENT"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resident_of",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inquilino/Residente Actual",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="estates.estate",
                        verbose_name="Edificio",
                    ),
                ),
            ],
        ),
    ]
